# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ast_transform` gem.
# Please instead update this file by running `bin/tapioca gem ast_transform`.


# pkg:gem/ast_transform#lib/ast_transform/source_map.rb:4
module ASTTransform
  class << self
    # pkg:gem/ast_transform#lib/ast_transform.rb:16
    def acronym(acronym); end

    # pkg:gem/ast_transform#lib/ast_transform.rb:12
    def acronyms; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:21
    def install; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:39
    def output_path; end

    # pkg:gem/ast_transform#lib/ast_transform.rb:35
    def output_path=(path); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:5
class ASTTransform::AbstractTransformation < ::Parser::AST::Processor
  include ::ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods
  extend ::ASTTransform::TransformationHelper::Methods

  # Used internally by Parser::AST::Processor to process each node. DO NOT OVERRIDE.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:19
  def process(node); end

  # Runs this transformation on +node+.
  # Note: If you want to add one-time checks to the transformation, override this, then call super.
  #
  # @param node [Parser::AST::Node] The node to be transformed.
  #
  # @return [Parser::AST::Node] The transformed node.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:14
  def run(node); end

  private

  # Processes the given +node+.
  # Note: If you want to do processing on each node, override this.
  #
  # @param node [Parser::AST::Node] The node to be transformed.
  #
  # @return [Parser::AST::Node] The transformed node.
  #
  # pkg:gem/ast_transform#lib/ast_transform/abstract_transformation.rb:33
  def process_node(node); end
end

# pkg:gem/ast_transform#lib/ast_transform.rb:9
ASTTransform::DEFAULT_OUTPUT_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:3
module ASTTransform::InstructionSequence
  class << self
    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:12
    def source_to_transformed_iseq(source, source_path); end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:5
    def using_bootsnap_compilation?; end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:28
    def write(string, pathname); end

    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence.rb:22
    def write_pathname(file_path); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/bootsnap_mixin.rb:9
module ASTTransform::InstructionSequence::BootsnapMixin
  # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/bootsnap_mixin.rb:10
  def input_to_storage(source, source_path); end
end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin.rb:9
module ASTTransform::InstructionSequence::Mixin
  # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin.rb:10
  def load_iseq(source_path); end
end

# Extends the default Prism parser builder to distinguish keyword arguments
# from hash literals in the AST.
#
# The upstream builder always emits :hash nodes for both `foo(bar: 1)` and
# `foo({ bar: 1 })`. Unparser uses the node type to decide whether to emit
# braces: :hash gets `{}`, :kwargs does not. Since Ruby 3.0+ treats these as
# semantically different (strict keyword/positional separation), we need the
# AST to preserve the distinction.
#
# pkg:gem/ast_transform#lib/ast_transform/kwargs_builder.rb:14
class ASTTransform::KwargsBuilder < ::Prism::Translation::Parser::Builder
  # pkg:gem/ast_transform#lib/ast_transform/kwargs_builder.rb:15
  def associate(begin_t, pairs, end_t); end
end

# pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin_utils.rb:4
module ASTTransform::MixinUtils
  class << self
    # pkg:gem/ast_transform#lib/ast_transform/instruction_sequence/mixin_utils.rb:6
    def try_super(target, method_sym, *args, &block); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/source_map.rb:5
class ASTTransform::SourceMap
  # Constructs a new SourceMap instance.
  #
  # Note: +source_ranges_ast+ and +transformed_ranges_ast+ must be equivalent ASTs.
  #
  # @param source_file_path [String] The path to the source file.
  # @param transformed_file_path [String] The path to the transformed file.
  # @param source_ranges_ast [Parser::AST::Node] A transformed AST that contains the source code ranges.
  # @param transformed_ranges_ast [Parser::AST::Node] A transformed AST that contains the ranges for the executed
  # code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:44
  def initialize(source_file_path, transformed_file_path, source_ranges_ast, transformed_ranges_ast); end

  # Retrieves the mapped line number for the given +line_number+.
  #
  # @param line_number [Integer] The line number in the executed code to be mapped to the source.
  #
  # @return [Integer|nil] The mapped line number, otherwise nil if not found.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:62
  def line(line_number); end

  # Retrieves the line count for the executed code.
  #
  # @return [Integer] The line count.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:69
  def line_count; end

  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:55
  def source_file_path; end

  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:55
  def source_map; end

  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:55
  def transformed_file_path; end

  private

  # Recursively look for node represented by +indexes+ in +node+. If not found, goes back +depth+ nodes and search for
  # the node pointed to by +indexes+.
  #
  # @param node [Parser::AST::Node] The node to search into. This must be a node in the +@source_ranges_ast+.
  # @param indexes [Array<Integer>] Child indexes pointing to the node we're looking for in +node+.
  # @param depth [Integer] Number of nodes to go up to search for the node pointed to by +indexes+.
  #
  # @return [Parser::AST::Node|nil] The node found, nil otherwise.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:130
  def approximate_dig_last_valid_node(node, indexes, depth = T.unsafe(nil)); end

  # Builds the source map.
  #
  # @return [Hash] A Hash containing line numbers from executed code to source code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:99
  def build_source_map; end

  # Recursively look for the node represented by +indexes+ in the children of +node+. If not found, returns the last
  # valid node.
  #
  # @param node [Parser::AST::Node] The node to look into.
  # @param indexes [Array<Integer>] The array of indexes pointing to the child node to be retrieved from +node+.
  #
  # @return [Parser::AST::Node|nil] The node if found, nil otherwise.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:211
  def dig_last_valid_node(node, indexes); end

  # Finds the index for the last valid node represented by +indexes+ in the children of +node+.
  #
  # @param node [Parser::AST::Node] The current node to search in.
  # @param indexes [Array<Integer>] The array of indexes pointing to the child node to be retrieved from +node+.
  #
  # @return [Integer|nil] The index of the node if found, nil otherwise.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:194
  def dig_last_valid_node_index(node, indexes); end

  # Recursively look for the node represented by +indexes+ in the children of +node+.
  #
  # @param node [Parser::AST::Node] The node to look into.
  # @param indexes [Array<Integer>] The array of indexes pointing to the child node to be retrieved from +node+.
  #
  # @return [Parser::AST::Node|nil] The node if found, nil otherwise.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:226
  def dig_node(node, indexes); end

  # Extracts SourceMap data from the given node.
  #
  # @param node [Parser::AST::Node] The node containing ranges for the executed code.
  #
  # @return [void]
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:80
  def extract_source_map_data(node, indexes); end

  # Recursively search the children of +node+ for an equivalent +queried_node+.
  #
  # @param node [Parser::AST::Node] The current node to search in.
  # @param queried_node [Parser::AST::Node] The equivalent node to search for.
  #
  # @return [Parser::AST::Node|nil] The found node from the +node+ graph, nil otherwise.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:152
  def search_node(node, queried_node); end

  # Recursively search the given +node+ for a range.
  #
  # @param node [Parser::AST::Node] The current node to search in.
  # @param max_range [Integer|nil] The max range to consider valid. Nil means any range is valid. If 1, only ranges
  # which span one line will be considered, etc...
  #
  # @return [Parser::Source::Range|nil] The range, or nil if no range was found. This occurs when the tree contains
  # no ranges, i.e. they're all virtually built nodes.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:172
  def search_range(node, max_range = T.unsafe(nil)); end

  # Retrieves the source line for the given +line_number+ in the executed code.
  #
  # @param line_number [Integer] The line number in the executed code.
  #
  # @return [Integer|nil] The line number in the source code, or nil if cannot be mapped.
  #
  # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:108
  def source_line(line_number); end

  class << self
    # Retrieves the SourceMap for the given +file_path+.
    #
    # @param file_path [String] The transformed file path.
    #
    # @return [SourceMap|nil] The associated source map.
    #
    # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:24
    def for_file_path(file_path); end

    # Registers the given SourceMap.
    #
    # @param source_map [SourceMap] The source map to be registered.
    #
    # @return [void]
    #
    # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:12
    def register_source_map(source_map); end

    private

    # pkg:gem/ast_transform#lib/ast_transform/source_map.rb:30
    def source_maps; end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/transformation.rb:8
class ASTTransform::Transformation < ::ASTTransform::AbstractTransformation
  private

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:69
  def extract_transformation(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:63
  def extract_transformations(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:38
  def next_child(node, index); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:34
  def previous_child(node, index); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:13
  def process_node(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:42
  def process_node_helper(node, previous_node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:99
  def require_path(const_name); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:86
  def require_transformation(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:51
  def transform_node?(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:57
  def transformable_node?(node); end

  # pkg:gem/ast_transform#lib/ast_transform/transformation.rb:112
  def try_const_get(const_name); end
end

# pkg:gem/ast_transform#lib/ast_transform/transformation.rb:9
ASTTransform::Transformation::TRANSFORM_AST = T.let(T.unsafe(nil), Parser::AST::Node)

# pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:5
module ASTTransform::TransformationHelper
  include ::ASTTransform::TransformationHelper::Methods

  mixes_in_class_methods ::ASTTransform::TransformationHelper::Methods

  class << self
    # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:6
    def included(base); end
  end
end

# pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:11
module ASTTransform::TransformationHelper::Methods
  # pkg:gem/ast_transform#lib/ast_transform/transformation_helper.rb:12
  def s(type, *children, **properties); end
end

# pkg:gem/ast_transform#lib/ast_transform/transformer.rb:9
class ASTTransform::Transformer
  # Constructs a new Transformer instance.
  #
  # @param transformations [Array<ASTTransform::AbstractTransformation>] The transformations to be run.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:13
  def initialize(*transformations); end

  # Builds the AST for the given +source+.
  #
  # @param source [String] The input source code.
  # @param file_path [String] The file_path. This is important for source mapping in backtraces.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:23
  def build_ast(source, file_path: T.unsafe(nil)); end

  # Builds the AST for the given +file_path+.
  #
  # @param file_path [String] The input file path.
  #
  # @return [Parser::AST::Node] The AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:33
  def build_ast_from_file(file_path); end

  # Transforms the given +source+.
  #
  # @param source [String] The input source code to be transformed.
  #
  # @return [String] The transformed code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:43
  def transform(source); end

  # Transforms the given +ast+.
  #
  # @param ast [Parser::AST::Node] The input AST to be transformed.
  #
  # @return [Parser::AST::Node] The transformed AST.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:85
  def transform_ast(ast); end

  # Transforms the give +file_path+.
  #
  # @param file_path [String] The input file to be transformed. This is required for source mapping in backtraces.
  # @param transformed_file_path [String] The file path to the transformed file.
  #
  # @return [String] The transformed code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:55
  def transform_file(file_path, transformed_file_path); end

  # Transforms the given +source+ in +file_path+.
  #
  # @param source [String] The input source code to be transformed.
  # @param file_path [String] The file path for the input +source+. This is required for source mapping in backtraces.
  # @param transformed_file_path [String] The file path to the transformed filed. This is required to register the
  # SourceMap.
  #
  # @return [String] The transformed code.
  #
  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:68
  def transform_file_source(source, file_path, transformed_file_path); end

  private

  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:93
  def create_buffer(source, file_path); end

  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:100
  def parser; end

  # pkg:gem/ast_transform#lib/ast_transform/transformer.rb:105
  def register_source_map(source_file_path, transformed_file_path, transformed_ast, transformed_source); end
end

# pkg:gem/ast_transform#lib/ast_transform/version.rb:2
ASTTransform::VERSION = T.let(T.unsafe(nil), String)
