# Generated by dev from dependencies.rb. Do not edit.
# Add or change gems in dependencies.rb and run `dev update-deps`.

source "https://rubygems.org"
ruby "3.3.10"
gem "sorbet-runtime"

group :development do
  gem "sorbet"
  gem "tapioca", require: false
end

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "rake"
  gem "rspock", "~> 2.3"
  gem "simplecov", "~> 0.22"
end
