# Generated by dev from dependencies.rb. Do not edit.
# Add or change gems in dependencies.rb and run `dev update-deps`.

source "https://rubygems.org"
ruby "3.3.10"
gem "sorbet-runtime"

group :development do
  gem "sorbet"
  gem "tapioca", require: false
  gem "rubocop", require: false
  gem "rubocop-shopify", require: false
  gem "rubocop-sorbet", require: false
end

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "rake"
  gem "rspock", "~> 3.0"
  gem "simplecov", "~> 1.0"
  gem "simplecov-cobertura", "~> 4.0", require: false
  gem "simplecov-sorbet", "~> 0.2", require: false
end
